//REDUX REDUCERS AND ACTIONS CONSTANTS
export const SET_USER = 'SET_USER';
export const IS_USER_SIGNED_IN = 'IS_USER_SIGNED_IN';
export const SET_LOGIN_CREDENTIDALS = 'SET_LOGIN_CREDENTIDALS';
export const SET_DEVICE_ID = 'SET_DEVICE_ID';
export const SET_POPUP = 'SET_POPUP';
export const SET_EVENTS = 'SET_EVENTS';
export const SET_MODAL_ALERT = 'SET_MODAL_ALERT';
export const SET_FILTERS = 'SET_FILTERS';
export const SET_AXIOS_REQUEST = 'SET_AXIOS_REQUEST';
export const FIRST_TIME_OPENING = 'FIRST_TIME_OPENING';
export const TOGGLE_ADVERTISEMENT = 'TOGGLE_ADVERTISEMENT';
export const SET_COMPETITION = 'SET_COMPETITION';
export const SET_BELL_COUNT = 'SET_BELL_COUNT';
export const TOGGLE_SUBSCRIBE = 'TOGGLE_SUBSCRIBE';

export const SET_WEB_COUPONS = 'SET_WEB_COUPONS';
